### ISSUE TITLE
Sprint 2 Review

### ISSUE THREAD

**Issue by mpelletiervaillant-zz** [z-web-unit/web-app#17]
This week, we worked on establish the functionality of the app as well as continue researching the market. We sketched the app layout, created user stories and brainstormed logo ideas.

**Comment by mpelletiervaillant-zz** [comment]
This week, we completed all thee tasks on time. It helped that we clearly established who was in charge of specific tasks and we all reviewed each other's work before marking it as complete. I trust my team mates to complete their portion of work on time, which is awesome!!!

**Comment by frankmitts** [comment]
Went very well, got everything done on time. The team was very reliable to get everything done on time and communicate throughout the week.

**Comment by SridharShrinidhi** [comment]
We completed the tasks on time and I felt we communicated well in class and via slack. As a team, we rely on each other to complete assigned tasks and it helps that we have open communication.

**Comment by SridharShrinidhi** [comment]
@thomasjbradley our sprint 2 review

**Comment by thomasjbradley** [comment]
👍
