### ISSUE TITLE
Sprint 3 Review

### ISSUE THREAD

**Issue by mpelletiervaillant-zz** [z-web-unit/web-app#31]

**Comment by mpelletiervaillant-zz** [comment]
This week, we completed everything on time again. We worked well together in asking for feedback. Next week, it would be cool if we could add more tasks if we see we are getting a lot done as the week goes by.

**Comment by frankmitts** [comment]
Got everything done ahead of time and we have the interactive XD ready to test.
We just had to fix a couple of issues within our xd file.

**Comment by SridharShrinidhi** [comment]
We set up the tasks for each person and we completed it on time. We did user testing in class and made changes to our wireframes based on the feedback.

**Comment by SridharShrinidhi** [comment]
Hi @thomasjbradley, our sprint 3 review.
